"""Declarative base, naming convention and mixins (§9).

Explicit constraint naming is not cosmetic. Alembic's autogenerate compares
reflected database constraints against the model, and PostgreSQL derives
constraint names automatically while SQLite does not — without a fixed
convention, autogenerated migrations differ between dialects and a migration
that works locally fails on the VPS (or vice versa). Naming them here makes
migrations reproducible on both.

The mixins encode platform-wide invariants so no model can forget them:

* every row has a time-ordered UUID primary key (§82),
* every row records when it was created and last updated, in UTC (§75),
* rows that must survive for audit/retention reasons can be soft-deleted (§83).

Financial records must **not** use :class:`SoftDeleteMixin`: §83 forbids
casually removing financial history, and a ``deleted_at`` flag invites exactly
that. It is intended for user-facing collections (saved views, notification
preferences) where deletion is a legitimate product feature.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from typing import Any, ClassVar, Final

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from arb_core.clock import utc_now
from arb_core.db.sql_types import GUID, JSONType, PreciseDecimal, UTCDateTime
from arb_core.identifiers import uuid7

__all__ = [
    "NAMING_CONVENTION",
    "Base",
    "SoftDeleteMixin",
    "TimestampMixin",
    "UUIDPrimaryKeyMixin",
]

#: Deterministic constraint/index names, shared by every dialect (§9, §141).
NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
    # Index names that include a "where" clause need a stable, short suffix.
    "ix_partial": "ixp_%(column_0_label)s",
}


class Base(DeclarativeBase):
    """Base class for every ORM model in the platform.

    ``type_annotation_map`` makes the safe choice the default: a model that
    declares ``Mapped[Decimal]`` without naming a column type still gets exact
    fixed-point storage rather than a float, and ``Mapped[datetime]`` still gets
    timezone-aware UTC (§74, §75).
    """

    metadata: ClassVar[MetaData] = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map: ClassVar[dict[Any, Any]] = {
        Decimal: PreciseDecimal(38, 18),
        datetime: UTCDateTime,
        uuid.UUID: GUID,
        dict[str, Any]: JSONType,
    }


class UUIDPrimaryKeyMixin:
    """Time-ordered UUID primary key.

    UUIDv7 keeps insert-heavy tables (``orders``, ``order_fills``,
    ``opportunities``) append-mostly in the B-tree instead of scattering writes
    across random pages the way UUIDv4 does (§82).
    """

    id: Mapped[uuid.UUID] = mapped_column(
        GUID,
        primary_key=True,
        default=uuid7,
        nullable=False,
    )


class TimestampMixin:
    """Creation and last-modification timestamps, always aware UTC (§75).

    Defaults are applied Python-side rather than via ``server_default`` so the
    value is identical on every dialect and is known to the ORM immediately
    after ``flush()`` without an extra round-trip.
    """

    created_at: Mapped[datetime] = mapped_column(
        UTCDateTime,
        nullable=False,
        default=utc_now,
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        UTCDateTime,
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
        index=True,
    )


class SoftDeleteMixin:
    """Opt-in soft deletion (§9).

    See the module docstring: do **not** apply this to financial records.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(
        UTCDateTime,
        nullable=True,
        default=None,
        index=True,
    )

    @property
    def is_deleted(self) -> bool:
        """``True`` once the row has been soft-deleted."""
        return self.deleted_at is not None
