"""Pydantic request/response contracts (§67, §68)."""

from __future__ import annotations

from arb_api.schemas.auth import (
    ChangePasswordRequest,
    LoginRequest,
    LoginResponse,
    MfaConfirmRequest,
    MfaDisableRequest,
    MfaEnrollmentResponse,
    MfaLoginRequest,
    MfaStatusResponse,
    PasswordChangeResponse,
    PasswordResetConfirmRequest,
    PasswordResetRequest,
    PasswordResetResponse,
    RefreshRequest,
    RegisterRequest,
    RegisterResponse,
    ResendVerificationRequest,
    SessionListResponse,
    SessionSummary,
    TokenSet,
    UserSummary,
    VerifyEmailRequest,
)
from arb_api.schemas.common import (
    ApiIndex,
    ErrorDetail,
    ErrorEnvelope,
    MessageResponse,
    PaginatedResponse,
    ResourceGroup,
)
from arb_api.schemas.health import ComponentHealth, HealthResponse, LivenessResponse
from arb_api.schemas.system import SystemInfo, WorkersResponse, WorkerSummary

__all__ = [
    "ApiIndex",
    "ChangePasswordRequest",
    "ComponentHealth",
    "ErrorDetail",
    "ErrorEnvelope",
    "HealthResponse",
    "LivenessResponse",
    "LoginRequest",
    "LoginResponse",
    "MessageResponse",
    "MfaConfirmRequest",
    "MfaDisableRequest",
    "MfaEnrollmentResponse",
    "MfaLoginRequest",
    "MfaStatusResponse",
    "PaginatedResponse",
    "PasswordChangeResponse",
    "PasswordResetConfirmRequest",
    "PasswordResetRequest",
    "PasswordResetResponse",
    "RefreshRequest",
    "RegisterRequest",
    "RegisterResponse",
    "ResendVerificationRequest",
    "ResourceGroup",
    "SessionListResponse",
    "SessionSummary",
    "SystemInfo",
    "TokenSet",
    "UserSummary",
    "VerifyEmailRequest",
    "WorkerSummary",
    "WorkersResponse",
]
